# Generated by Django 4.1.5 on 2023-01-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='email',
            new_name='participants',
        ),
    ]
